#define NO_PATH 1
#define FILE_NOT_OPENED 2
#define USED_SAVED_WORD 3
#define FAILED_TO_ALLOCATE_MEMORY 4
#define EXCEEDED_PERMISSIBLE_LENGTH 5
#define DEFINE_SYNTAX_ERROR 6
#define NAME_IS_DUPLICATE 7
#define USED_SAVED_WORD_AS_TAG 8
#define USED_MACRO_AS_DEFINE 9

void error_output(int error_code);